import React from 'react'
import Mapa from "./Fotos/Mapa.png";

function info() {
  return (
    <div>
        <div className='container'>
          <div className='row' style={{marginTop:50, marginBottom:50}}>
            <div className='col-md-6 d-flex align-items-start justify-content-start'>
              <div className='row'>
                <h1 id="Ventas" style={{fontWeight: 800, fontSize:43, marginBottom:25}}>¿Que Vendemos?</h1>
                <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>"En El Boliche buscamos traer a nuestra clientela una variada gama de productos de belleza, accesorios y prendas de
                moda. Todo esto a precios accequibles y de una forma tanto sencilla como segura, de esta manera generando confianza y una comunidad de clientes que nos permitan continuar creciendo."</p>
              </div>
            </div>
            <div className='col-md-6 d-flex align-items-start justify-content-start'>
              <div className='row'>
                <h1 id="How" style={{fontWeight: 800, fontSize:43, marginBottom:25}}>¿Cómo Funciona?</h1>
                <div className='d-flex align-items-start justify-content-start'>
                  <ol align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>
                    <li>Buscas el producto o promoción que quieras comprar.</li>
                    <li>Agregas tus productos al carrito de compras.</li>
                    <li>Inicias el proceso de pago.</li>
                    <li>Seleccionas envío a domicilio o presencial.</li>
                    <li>Si seleccionaste a domicilio se te pedirá la dirección.</li>
                    <li>Si seleccionaste presencial se te pedirán datos de contacto para coordinar un punto de entrega.</li>
                    <li>Una vez seleccinado tu método de entrega realizas el pago.</li>
                    <li>Recibes tu producto y revisas que todo se encuentre en orden.</li>
                  </ol>
                </div>
              </div>
            </div>
          </div>
            <h1 id="Ubicación" style={{fontWeight: 800, fontSize:43, marginBottom:25}}>Ubícanos</h1>
            <p style={{fontWeight: 500, fontSize:19, color:"grey"}}>Aquí podrás ver todas las comunas de Santiago que ACTUALMENTE califican para entregas presenciales. Los puntos de encuentro en dichas comunas se deben coordinar directamente una vez realizada la compra.</p>
            <div className='d-flex align-items-center justify-content-center' style={{marginTop: 50, marginBottom: 50}}>
              <img src={Mapa} height="400" style={{borderRadius:20}}/>
            </div>
            <h1 id="Términos" style={{fontWeight: 800, fontSize:43, marginBottom:25}}>Términos de Servicio</h1>
            
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"black", marginBottom:50}}>1. ¿Qé es este documento?</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Bienvenido a ElBoliche.cl. Estos términos y condiciones (en adelante, los “T&C”) regulan el acceso y uso, en Chile, pero desde donde sea que accedas y lo uses, a nuestro sitio web www.ElBoliche.cl (en adelante también “ElBoliche.cl” o el “Sitio”).</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Estos T&C aplican al uso que le des a ElBoliche.cl sin importar cuál sea la finalidad del mismo, como por ejemplo, para vitrinear, comparar precios, sacar ideas, inspirarte, informarte de características técnicas de los productos o servicios, y/o conocer o entender nuestra propuesta de valor. Te instamos enfáticamente a que leas estos T&C con atención. Si después de leerlos tienes cualquier duda, por favor contáctanos para ayudarte con ellos.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey", marginBottom:50}}>Es muy importante que tengas presente que, al acceder y usar ElBoliche.cl, estás aceptando estos T&C de manera íntegra y sin reservas, y que ellos forman parte inseparable, tanto del uso que hagas del Sitio como de cualquier compra de bienes o servicios, así como del agendamiento de estos últimos que realices a través del Sitio. Considera, por favor, que esto no viene de una intención de nuestra parte de querer hacer imposiciones unilaterales. Se trata de una cualidad esencial e inherente a la masividad de internet y el comercio electrónico. No podríamos hacerlo de otro modo. Por eso, si no estás de acuerdo con estos T&C, por favor no uses nuestro sitio porque, por el hecho de usarlo, se entenderá que los conoces y los has aceptado. Y si tienes una buena idea sobre cómo podemos mejorar estos T&C, por favor háznoslo saber.</p>
            
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"black", marginBottom:50}}>2. Autorización de uso</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey", marginBottom:50}}>En su esencia, ElBoliche.cl es un conjunto de aplicativos informáticos o softwares. Puedes usar gratuitamente nuestro software y aplicaciones para equipos móviles con el fin de visitar, comparar y adquirir, si lo deseas, los productos y servicios que te ofrecemos. Lo que no puedes hacer con los aplicativos informáticos o softwares del Sitio o sus aplicaciones móviles es intervenirlos, copiarlos ni distribuirlos. La sola visita del Sitio no te impone obligación alguna, a menos que hayas expresado en forma inequívoca y mediante actos positivos, tu voluntad de adquirir uno o más bienes o servicios, en la forma indicada en estos T&C.</p>

            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"black", marginBottom:50}}>3. ¿Qué es ElBoliche.cl, quién vende en él y que leyes aplican?</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>ElBoliche.cl es un marketplace. En comercio electrónico, un marketplace es un sitio web de comercio electrónico en el que se comercializan productos y servicios ofrecidos por terceros distintos de quien opera el sitio (en adelante, cada uno, un “Vendedor”). Algunos sitios de marketplace comercializan tanto productos y servicios ofrecidos por Vendedores como ofrecidos por quien opera el sitio. En el Sitio, sólo comercializamos productos y servicios ofrecidos por Vendedores, aunque algunos de esos Vendedores son empresas vinculadas a nosotros, y, además, las compras que hagas en el Sitio pueden estar complementadas con beneficios y servicios que sí brindamos o prestamos nosotros. Cuando decimos nosotros, nos referimos a ElBoliche.cl SpA, RUT N°76.212.492-0, con domicilio en Av. Catedral 1.401, piso 14, oficina 1401, comuna de Santiago, región Metropolina, Chile,  (en adelante “ElBoliche.cl”), que es la empresa que opera la plataforma.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>La gestión de la venta de los productos y servicios que encontrarás en el Sitio es responsabilidad del Vendedor a quien hayas comprado, con independencia de las responsabilidades inherentes al uso del Sitio y la operación que de él hacemos. En la información de cada producto y servicio podrás ver quién es tu Vendedor, y si el producto o servicio y el Vendedor se encuentran en Chile o si, por el contrario, se trata de productos y servicios o Vendedores en o desde el exterior. De todas formas, ten presente que estaremos siempre a tu disposición para apoyarte con tus requerimientos y asegurar una respuesta de tu Vendedor. En caso de que lo necesites, puedes comunicarte con nosotros a través de la sección Mis Compras, o llamando a nuestro teléfono 600 329 2002, y con mucho gusto te atenderemos.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey", marginBottom:50}}>Tanto las compras realizadas en el Sitio como el uso que de él hagas, y la aplicación de estos T&C, están sujetos a las leyes chilenas, especialmente, a las normas que protegen los derechos de los consumidores. Por otra parte, en los casos en que existan contradicciones o incertidumbres en estos T&C, privilegiaremos la interpretación que te sea más favorable, por sobre otra que no lo sea. Asimismo, gozarás de los beneficios adicionales que te otorgan estos T&C. En el Sitio podrás acceder a información sobre “beneficios ElBoliche.cl”, “costos y tipos de entrega” y otros. El objetivo es facilitarte el acceso e incrementar los beneficios de uso de ElBoliche.cl, que pueden variar periódicamente, sin afectar en caso alguno los derechos adquiridos por los consumidores.</p>
            
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"black", marginBottom:50}}>4. Comunicaciones electrónicas</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Toda comunicación promocional o publicitaria que te enviemos electrónicamente tendrá nuestra identidad como remitente y en el asunto detallará a qué se refiere. Además, tendrá un vínculo digital para que el destinatario, si lo desea, solicite la cancelación de envíos futuros a ese correo o número de teléfono, según corresponda, y guarde un comprobante de la solicitud. De esta forma, cesarán los mensajes al canal de contacto solicitado. También podrán contactarte a través de la plataforma de ElBoliche.cl los Vendedores y los Vendedores Vinculados de quienes hayas adquirido un producto o servicio, con el objeto de concretar la venta y/o coordinar lo que resulte necesario para ese fin. Los Vendedores Vinculados también podrán enviarte comunicaciones promocionales, conforme a lo establecido en la sección N° 11 de este documento.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey", marginBottom:50}}>Asimismo, si realizaste un pedido bajo la modalidad “despacho a domicilio”, es posible que el transportista encargado del despacho te contacte con el fin de que tu pedido sea entregado en tu domicilio de manera correcta y dentro del plazo establecido, según lo indicado en la sección N° 6 de este documento.</p>
            
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"black", marginBottom:50}}>5. Cómo comprar o contratar sevicios en este sitio</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>La adquisición de productos y servicios ofrecidos en ElBoliche.cl sólo puede ser realizada por personas que tengan capacidad legal para contratar, sean personas naturales o jurídicas. Al registrar a una persona jurídica como usuario del Sitio, deberás tener poder para contratar a nombre de la misma y de obligarla en los términos de estos T&C.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Para hacer compras o contratar servicios en este Sitio, deberás seguir los siguientes pasos:</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Selecciona los productos o servicios de tu interés y agrégalos al carro de compras. Es muy importante que, antes de comprar, verifiques las dimensiones del producto y del lugar donde lo instalarás, de ser aplicable.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Selecciona el tipo de despacho o de entrega y uno de los medios de pago disponibles en el proceso de compra. Esta información es fundamental para una correcta y oportuna entrega de tus productos en el lugar que hayas indicado para la entrega, por lo que es importante que ingreses los datos de manera completa, correcta y veraz. Podrás visualizar el costo de despacho de tu pedido al finalizar el proceso de compra y antes del pago. </p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Una vez hecha tu solicitud de compra, se desplegará en tu pantalla una descripción del producto o servicio, su precio, la fecha o rango de fechas de entrega según el método de envío seleccionado, el medio de pago, el precio de los productos incluidos en tu solicitud de compra, descuentos, costo de despacho si los hubiere y cualquier otro costo aplicable, y las demás condiciones de tu pedido, la que podrás revisar y guardar; y el número asociado a tu solicitud de compra. En caso de que ésta comprenda dos o más pedidos, recibirás un número por cada uno de esos pedidos. Te enviaremos esta información al correo electrónico que hayas indicado.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey", marginBottom:50}}>Te enviaremos, a la casilla de correo electrónico que hayas registrado, un documento con toda la información que podrías necesitar para ejercer todos tus derechos como consumidor. En caso de que necesites la boleta asociada a la transacción, podrás obtenerla en la sección “Mis Compras” de nuestro Sitio. Si tu compra incluye productos comercializados por un Vendedor que no sea un Vendedor Vinculado, recibirás la boleta con tu pedido y, si lo requieres, podrás solicitar una copia en la sección “Mis Compras”.</p>
            
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"black", marginBottom:50}}>6. Despacho y entrega de productos</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Si prefieres que despachemos los productos a una dirección específica dentro de la zona de cobertura, debes señalar el lugar de entrega y el tipo de despacho de entre aquellos que estén disponibles en ElBoliche.cl. Infórmate sobre el costo del despacho de forma desglosada del valor del producto, así como de los lugares de entrega disponibles, y el rango de tiempo que tardará el despacho o entrega, haciendo click en “Despacho a Domicilio o Retira tu Compra”.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Antes de ingresar la solicitud de compra, podrás consultar, en la publicación de cada producto en específico, el costo del despacho, de forma desglosada del valor del producto, así como los lugares de entrega disponibles y el rango de tiempo que tardará el despacho o entrega. Además, quien presta el servicio de despacho o entrega será ElBoliche.cl o los vendedores, directamente o a través de terceros, atendiendo el producto de que se trate, los factores logísticos y la elección manifestada por el cliente. Cualquiera sea el método de entrega o despacho, ElBoliche.cl atenderá todas tus consultas y requerimientos.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Si los productos están almacenados en diferentes lugares, podrán despacharse en forma separada, según la alternativa disponible que hayas escogido. Por tal motivo y, también, dependiendo del método de entrega que elijas al ingresar tu solicitud de compra, podrá existir más de un costo de despacho. En cualquier caso, podrás visualizar el costo total de despacho de tu pedido en el carro de compras, antes de realizar la transacción. Es muy importante que ingreses la dirección de envío de manera completa y exacta para que tu pedido sea entregado sin inconvenientes. Si no contamos con cobertura de transporte o logística al lugar al que quieras despachar un producto que quieras comprar, el Sitio no te dejará finalizar la solicitud de compra y te informará que tu pedido no puede ser entregado en la dirección solicitada.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>El despacho de tus productos se efectuará según el horario y condiciones informadas en la publicación de cada producto o servicio específico en el Sitio, antes de realizar la compra. Verifica que los productos correspondan a los que compraste y que estén en perfectas condiciones, antes de aceptarlos. Ten en cuenta que, para realizar la entrega de tu pedido de manera correcta y oportuna en el domicilio que hubieres indicado, es posible que el transportista a cargo te contacte al número telefónico que hubieres indicado en al registrarte.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Recuerda que el lugar físico donde se realiza la entrega debe asegurar las condiciones mínimas para el acceso del medio de transporte, esto es, disponibilidad de estacionamiento y horario de acceso, así como ascensor cuando el peso o el volumen de tus compras lo haga necesario.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Es indispensable que, antes de comprar, revises las dimensiones del producto, los accesos del domicilio y el lugar donde se entregará, de manera que la entrega pueda ser efectuada de forma adecuada. De no cumplirse estas condiciones, los productos se entregarán sólo en el primer piso. Si el lugar de despacho se encuentra en un edificio que no tiene ascensor, la entrega en pisos superiores sólo se efectuará hasta el cuarto piso, en la medida que exista factibilidad técnica para entregarlo en condiciones seguras. Si el edificio cuenta con ascensor, podremos entregar tu pedido en pisos superiores siempre que sus dimensiones y peso permitan el traslado en ascensor de manera segura. Sólo se trasladará tu pedido por escaleras o ascensores, de acuerdo con lo anterior. En ningún caso se considera desarmar puertas o ventanas del domicilio del cliente, ni la utilización de cuerdas u otros elementos para levantar los productos a pisos superiores. Los productos deben ser recibidos por una persona mayor de edad que deberá manifestar su aceptación, dejando constancia de sus datos y de cualquier observación respecto de las condiciones en que reciba el producto.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Al momento de entregar el pedido en la dirección que seleccionaste, el repartidor solicitará indicar el nombre y número de documento de identidad de quien recibe el pedido. Adicionalmente, es posible que te enviemos un código alfanumérico con el cual podrás validar la entrega del producto sin necesidad de indicar esos datos.  Si tu pedido es recibido por el conserje de tu edificio, él o ella pueden dar el número de rol único tributario de la comunidad. Ten en cuenta que, como medida de seguridad adicional, el repartidor tomará una fotografía de tu pedido afuera del domicilio o en conserjería, según corresponda.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Si no estás conforme con un producto al momento de la entrega, recházalo y registra tus comentarios, junto con tu nombre completo y el número de tu documento de identidad, y te contactaremos para revisar tu caso y ofrecerte una solución. Al entregar esta información, autorizas el tratamiento de estos datos personales de acuerdo a nuestra Política de Privacidad.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey", marginBottom:50}}>En caso de que no sea posible efectuar una entrega debido a errores o falta de información en la dirección o en los datos de contacto proporcionados por el cliente, el pedido será cancelado. En caso de querer realizar una rectificación para poder reactivar la entrega de tu producto, por favor contacta a nuestro Servicio al Cliente para realizar la solicitud y obtener más información.</p>
            
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"black", marginBottom:50}}>7. Derechos que tienes al comprar en ElBoliche.cl</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Nuestra prioridad es que te sientas contento y satisfecho con las compras que realizas. También, nos interesa que tengas la tranquilidad y sientas nuestro respaldo en todo momento. Por eso, además de las garantías legales y las ofrecidas por los fabricantes y por los Vendedores de los productos que se comercializan en nuestro Sitio, tenemos beneficios adicionales para entregarte una experiencia realmente satisfactoria. En relación con lo anterior, y no obstante las condiciones que se indican como requisitos para el cambio o la devolución de un producto, ElBoliche.cl velará por buscar la mejor solución para sus clientes, pudiendo hacer excepciones en su beneficio.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>GARANTÍA LEGAL</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Si tu producto presentare fallas o defectos dentro de los 6 meses siguientes a la fecha en que fue recibido, podrás optar libremente entre su reparación gratuita o, previa restitución, su cambio o la devolución de la cantidad pagada, a menos  que la falla o defecto se hubiere producido por un acto o hecho no imputable al Vendedor o al fabricante (como por ejemplo, si se hubiere usado, armado o instalado incorrectamente). Ten en cuenta que el Vendedor de tu producto tendrá el derecho de hacer una revisión técnica de éste de manera previa a que puedas ejercer las opciones expuestas, para poder determinar el origen de la falla reclamada. Si tu producto cuenta con una garantía del fabricante, se aplicará el plazo de esa garantía, si dicho plazo fuera mayor.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Si el producto es perecible o está naturalmente destinado a ser usado o consumido en un periodo breve, como los alimentos y bebidas, el plazo de devolución será el impreso en el producto o en su envoltorio o, en su defecto, será de 7 días. Si el proveedor del producto o servicio ofrece una garantía voluntaria, podrás optar, libremente, por ejercer la garantía del proveedor o la garantía legal. El plazo para ejercer la garantia legal, así como el plazo para solicitar la garantía del proveedor, se suspenderán durante el tiempo en que esté siendo ejercida cualquiera de las garantías. Asimismo, estos plazos se suspenderán por el tiempo en que el bien no perecible esté siendo reparado en ejercicio de la garantía, hasta que se complete su reparación.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Para ejercer tu derecho a la garantía legal, puedes entregar el producto directamente en las ubicaciones habilitadas para este efecto, las que se encuentran informadas en el Sitio, en la sección “Mis compras”. Para productos de mayor tamaño, tales como refrigeradores y lavadoras, puedes ingresar tu solicitud de retiro del producto a través del Sitio en la sección “Mis compras” Del Sitio. Ante cualquier duda puedes revisar las Preguntas Frecuentes en la sección “Centro de Ayuda” de ElBoliche.cl; o bien, puedes ingresar tu consulta en la sección “Mis Compras” del Sitio.  Si el producto se hubiere deteriorado por mal uso del consumidor, no se aplicará esta garantía. Asimismo, deberás presentar algún comprobante que acredite de manera fehaciente la compra realizada.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Para efectos de la garantía legal, se considerará que hay una falla o defecto:</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>a) Cuando los productos sujetos a normas de seguridad o calidad de cumplimiento obligatorio no cumplan las especificaciones correspondientes;</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>b) Cuando los materiales, partes, piezas, elementos, sustancias o ingredientes que constituyan o integren los productos no correspondan a las especificaciones que ostenten o a las menciones del rotulado;</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>c) Si cualquier producto, por deficiencias de fabricación, elaboración, materiales, partes, piezas, elementos, sustancias, ingredientes, estructura, calidad o condiciones sanitarias, en su caso, no sea enteramente apto para el uso o consumo al que está destinado o al que el proveedor hubiese señalado en su publicidad;</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>d) Cuando el proveedor (es decir, tu Vendedor) y consumidor hubieren convenido que los productos objeto del contrato deban reunir determinadas especificaciones y esto no ocurra;</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>e) Cuando después de la primera vez de haberse hecho efectiva la garantía y prestado el servicio técnico correspondiente, subsistieren las deficiencias que hagan al bien inapto para el uso o consumo a que se refiere la letra c). Sin perjuicio de lo anterior, no será necesario hacer efectiva la garantía voluntaria otorgada por el proveedor para ejercer la garantía legal. En este evento, podrás optar entre la reposición del producto o la devolución de la cantidad pagada. Este derecho subsistirá para el evento de presentarse una deficiencia distinta a la que fue objeto del servicio técnico, o volviere a presentarse la misma, dentro de los plazos a que se refiere el artículo siguiente;</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>f) Cuando la cosa objeto del contrato tenga defectos o vicios ocultos que imposibiliten el uso a que habitualmente se destine;</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>g) Cuando la ley de los metales en los artículos de orfebrería, joyería y otros sea inferior a la que en ellos se indique. Para estos efectos se considerará que es un solo bien aquel que se ha vendido como un todo, aunque esté conformado por distintas unidades, partes, piezas o módulos, no obstante que éstas puedan o no prestar una utilidad en forma independiente unas de otras. Sin perjuicio de ello, tratándose de su reposición, ésta se podrá efectuar respecto de una unidad, parte, pieza o módulo, siempre que sea por otra igual a la que se restituye.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>En el caso de productos que han sido informados como imperfectos, usados, reparados, abiertos, de segunda selección, remanufacturados, con alguna deficiencia, o en cuya fabricación o elaboración se hayan utilizado partes o piezas usadas, entre otros, que sean comprados en esa condición a un precio reducido, no procederá el cambio ni su envío a servicio técnico, ni la devolución del producto por motivos de garantía legal. Sin embargo, para esos casos, algunos Vendedores pueden ofrecer garantías voluntarias de acuerdo a las condiciones que ellos publiquen en la página del producto.  </p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>SATISFACCIÓN GARANTIZADA: EN FALABELLA.COM, CAMBIAR DE OPINIÓN NO ES UN PROBLEMA</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Si te arrepentiste del producto que compraste, prefieres otro, no es de tu talla, o simplemente cambiaste de opinión, no te preocupes, puedes devolverlo sin problemas. Nuestro compromiso de Satisfacción Garantizada te permite devolver tu producto hasta 30 días después de la fecha en que lo hayas recibido, sin costo adicional, en puntos de devolución autorizados, los cuales se encuentran informados en la sección “Mis compras” del Sitio. Para velar por tu seguridad y la de todos nuestros clientes, no se permitirá la devolución de alimentos, bebidas, suplementos alimenticios, vitaminas, ni de ningún otro producto análogo y/o de sus respectivas materias primas. Asimismo, no se aceptará la devolución de bienes intangibles, consumibles o que hayan caducado.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Asimismo, salvo que se trate de productos cerrados y sin haberse abierto, no se podrán devolver artículos de ropa interior, juguetes sexuales ni nada que, conforme a su uso natural, se emplee en contacto directo con partes del cuerpo de modo tal que para otro usuario de dicho producto se pueda derivar un riesgo de infección o contagio.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey", marginBottom:50}}>Considera que esta garantía no aplica con respecto a los productos a pedido o confeccionados a medida,  productos digitales que se entregan mediante una descarga electrónica, plantas y pinturas de un color a pedido.. En el caso de productos que han sido informados como usados, abiertos, reparados, de segunda selección, remanufacturados, con alguna deficiencia, o en cuya fabricación o elaboración se hayan utilizado partes o piezas usadas, entre otros, que sean comprados en esa condición y con un precio reducido, no procederá la devolución del producto.</p>
            
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"black", marginBottom:50}}>8. Plazos de devolución del dinero</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Cuando corresponda que te reembolsemos dinero por algún motivo, éste será devuelto a través del mismo medio de pago utilizado en la compra. Los plazos para el procesamiento de tu solicitud de devolución de dinero se contarán a partir de la emisión de la nota de crédito, o del documento que legalmente corresponda, y varían según el medio de pago que hayas utilizado. A continuación, puedes revisar los plazos involucrados, según el medio de pago utilizado para efectuar la compra:</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Tarjeta de crédito de otros bancos o entidades financieras: el reembolso dependerá de los tiempos de procesamiento de la respectiva entidad bancaria. En promedio, dichas entidades consideran un plazo de 3 días hábiles para el reembolso.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Tarjetas de débito o dinero efectivo: el tiempo dependerá del contacto con el cliente por parte de un ejecutivo que gestionará el depósito a su cuenta bancaria.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>En general, se realiza en un máximo de quince (15) días hábiles bancarios. Si, a pesar de todos nuestros intentos para contactar al cliente ello no fuera posible porque los datos no están actualizados, porque el cliente no atiende, o por cualquier otro motivo, Falabella procederá a emitir un vale vista por el monto de la compra, el que podrá ser retirado por el titular de la compra en un plazo de 120 días desde su emisión, en cualquier sucursal del Banco de Chile.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey", marginBottom:50}}>Gift card: la devolución se realizará dentro de 24 horas.</p>
            
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"black", marginBottom:50}}>9. Derecho de retracto</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>El consumidor podrá poner término a los contratos celebrados en ElBoliche.cl, sin expresión de causa, en el plazo de 10 días contados a partir de la recepción del producto.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey", marginBottom:50}}>Sin embargo, el consumidor no podrá terminar unilateralmente los contratos cuando el producto, por su naturaleza: i) no pueda ser devuelto o pueda deteriorarse o caducar con rapidez; ii) hubiese sido confeccionado conforme a las especificaciones del consumidor; o, iii) sea un producto de uso personal.</p>
            
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"black", marginBottom:50}}>10. Términos de contratos</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey", marginBottom:50}}>Podrás poner término a los contratos de adhesión de tracto sucesivo según la normativa aplicable y cumpliendo las condiciones particulares que, al respecto, pueda contener el respectivo contrato. En caso de ser legalmente procedente la terminación, los medios y la oportunidad para hacerlo serán informadas previamente en dichos contratos. En cualquier caso, no condicionaremos dicho término al pago de montos adeudados o a la restitución de bienes, si correspondiere.</p>
            
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"black", marginBottom:50}}>11. Políticas de seguridad</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>ElBoliche.cl adoptará las medidas que sean necesarias para resguardar la seguridad de tus datos personales y de tu clave secreta en conformidad con la legislación viente y nuestra Política de Privacidad. En caso de detectarse cambios en la información que has registrado en el Sitio, o bien, ante cualquier irregularidad en las transacciones relacionadas con tu identificación o la del medio de pago, o simplemente como medida de protección a tu identidad, nuestros ejecutivos podrán contactarte por vía telefónica o correo electrónico, a fin de corroborar tus datos e intentar evitar posibles fraudes.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey", marginBottom:50}}>En caso de no poder establecer el contacto en un plazo de 72 horas, por tu propia seguridad, tu solicitud de compra efectuada en nuestro Sitio no será confirmada. Te informaremos vía telefónica o correo electrónico que tu pedido ha quedado sin efecto por no poder confirmar tu identidad o el medio de pago ofrecido. Además, los comprobantes de las gestiones realizadas para contactarte y poder confirmar la operación estarán disponibles en nuestras oficinas durante 30 días, para que puedas confirmar la solicitud de compra.</p>

            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"balck", marginBottom:50}}>12. Autorización para el tratameinto de datos personales</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Para ElBoliche.cl, ofrecerte una experiencia de compra que se acomode a tus intereses y necesidades particulares es tan importante como cuidar los datos personales que requerimos tratar para ello.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey", marginBottom:50}}>Por ello, solo trataremos tu información personal con una base de legalidad adecuada y en conformidad con la Política de Privacidad de ElBoliche.cl, que explica para qué tratamos y cómo protegemos tus datos, y te entrega toda la información necesaria que conozcas y puedas ejercer tus derechos como titular de tus datos personales.</p>
            
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"balck", marginBottom:50}}>13. Alcance de los precios infromados en este sitio</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Los precios ofrecidos en ElBoliche.cl corresponden exclusivamente al precio del producto o servicio ofrecido, impuestos incluidos, y no incluyen gastos de transporte, manejo, envío, instalación (a menos que hayas pagado por ese servicio, o que haya estado expresamente incluido con la compra de tu producto), accesorios (salvo aquellos que hayan estado expresamente incluidos con la compra de tu producto) u otros que fueren aplicables, los que se informarán en el carro de compras.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Los Vendedores de nuestra plataforma hacen sus mejores esfuerzos para que los precios que publican en el Sitio para sus productos y servicios sean los correctos, y así ocurre en casi la totalidad de los casos y ocasiones. Sin embargo, a pesar de todos esos esfuerzos, eventualmente podrían ocurrir errores humanos o de sistema en los precios publicados por los Vendedores. En relación con lo anterior, te invitamos a que tus transacciones en el Sitio se ajusten a la buena fe que rige en los contratos en nuestro país. Por lo tanto, ante un eventual error manifiesto en la publicación de un precio, y considerando que en el Sitio se comercializan productos para ser adquiridos por consumidores, esto es, para tu consumo personal o de tu núcleo familiar, es posible que no podamos procesar aquellas solicitudes de compra respecto de las cuales existan motivos fundados para estimar que han sido ingresadas con fines comerciales, en aprovechamiento de un error evidente, o en cualquier sentido contrarias a la buena fe que, de acuerdo a la ley, debe existir en la celebración y ejecución de los contratos. Si se detectare un error de precio en alguna publicación, te contactaremos a la brevedad posible para validar tu solicitud de compra al precio correcto, o bien, para dejar sin efecto la solicitud de compra ingresada, según tú prefieras.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Una vez confirmada una solicitud de compra, ElBoliche no modificará las condiciones bajo las cuales haya contratado con los consumidores en este Sitio. Mientras aparezcan en este Sitio, los precios informados estarán a tu disposición. Ellos podrían no ser los mismos que se ofrezcan en otros canales de venta de las Empresas ElBoliche o de los Vendedores de ElBoliche.cl, como tiendas físicas, catálogos, televisión, radio, u otros.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey", marginBottom:50}}>Cualquier cambio en las informaciones publicadas en este Sitio, incluyendo las referidas a mercaderías, servicios, precios, existencias y condiciones, promociones y ofertas, tendrá lugar antes de recibir una solicitud de compra, y sólo se referirá a operaciones futuras, sin afectar, en caso alguno, derechos adquiridos por los consumidores.</p>
            
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"black", marginBottom:50}}>14. Ofertas y promociones</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Las ofertas consisten en el ofrecimiento de bienes o servicios a precios rebajados en forma transitoria, en relación con los habituales del respectivo establecimiento. En tanto, las promociones consisten en el ofrecimiento de bienes y servicios en condiciones más favorables que las habituales, con excepción de aquellas que consistan en una simple rebaja de precio.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Las ofertas y las promociones disponibles en ElBoliche.cl son válidas únicamente respecto de aquellas compras que signifiquen actos de consumo; es decir, aquellos que tienen por objeto satisfacer una necesidad personal o de un núcleo familiar. En consecuencia, las ofertas y las promociones que aparecen en el Sitio no son válidas para aquellas solicitudes de compra que sean ingresadas con la posterior intención de revender o comercializar de cualquier forma los productos y servicios de que se trate.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Las ofertas y las promociones disponibles en este Sitio no serán necesariamente las mismas que ofrezcan otros canales de venta de los Vendedores de ElBoliche.cl. En las promociones que consistan en la entrega gratuita o rebajada de un producto por la compra de otro, el despacho del bien que se entregue gratuitamente o a precio rebajado se hará en el mismo lugar al cual se despache el producto comprado, salvo que solicites, al aceptar la promoción u oferta, que los productos se remitan a direcciones distintas, en cuyo caso deberás pagar el valor del despacho de ambos productos. No se podrá participar en estas promociones sin adquirir conjuntamente todos los productos comprendidos en ellas.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey", marginBottom:50}}>Con respecto a productos que se encuentren en oferta o en promoción, podrá aplicarse un máximo distinto de unidades que podrán ser comprados por cada cliente, lo cual será informado en las condiciones que sean aplicables a cada actividad.</p>

            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"black", marginBottom:50}}>15. Propiedad intelectual</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Todos los contenidos incluidos en este Sitio, como textos, material gráfico, logotipos, íconos de botones, códigos fuente, imágenes, audio clips, descargas digitales, compilaciones de datos, y en general el “look and feel” del Sitio son propiedad de ElBoliche.cl SpA o de sus proveedores de contenidos, y están protegidos por las leyes aplicables y convenios internacionales vigentes sobre propiedad intelectual. Los materiales gráficos, logotipos, encabezados de páginas, frases publicitarias, iconos de botones, textos escritos y nombres de servicios incluidos en este Sitio son marcas comerciales, creaciones o imágenes comerciales de propiedad de ElBoliche S.A. en Chile y en otros países. Dichas marcas, creaciones e imágenes comerciales no se pueden usar con relación a ningún producto o servicio que pueda causar confusión entre los clientes y en ninguna forma que desprestigie o desacredite a las Empresas ElBoliche. Las demás marcas comerciales que no sean de propiedad de ElBoliche S.A. y que aparezcan en este Sitio pertenecen a sus respectivos dueños.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Todos los derechos no expresamente otorgados en estos T&C son reservados por ElBolihe.cl SpA o sus cesionarios, proveedores, editores, titulares de derechos u otros proveedores de contenidos. Ningún producto, imagen o sonido pueden ser reproducidos, duplicados, copiados, vendidos, revendidos, visitados o explotados para ningún fin, en todo o en parte, sin el consentimiento escrito previo de ElBoliche.cl SpA. No se puede enmarcar o utilizar técnicas de enmarcación para encerrar alguna marca comercial, logotipo u otra información registrada o patentada (incluyendo imágenes, texto, disposición de páginas, o formulario) de ElBoliche S.A., sin nuestro consentimiento escrito previo. Tampoco se puede usar meta etiquetas ni ningún otro “texto oculto” que use el nombre o marcas comerciales de ElBoliche S.A., sin autorización escrita previa de esta empresa. Se prohíbe hacer un uso indebido de este Sitio o de estas marcas, licencias o patentes. Lo anterior, sin perjuicio de las excepciones expresamente señaladas en las leyes aplicables.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey", marginBottom:50}}>ElBoliche.cl respeta la propiedad intelectual de otros. Si adviertes una posible vulneración de los derechos de Propiedad Intelectual en los productos ofrecidos por nuestros vendedores o crees que tu trabajo ha sido replicado en forma tal que constituiría una vulneración de tus derechos de propiedad intelectual, contáctate con nosotros al 600 329 2002.</p>
            
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"black", marginBottom:50}}>16. Representantes de ElBoliche.cl</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey", marginBottom:50}}>Para facilitar el envío de cualquier presentación, consulta o reclamo sobre el uso de este Sitio o las transacciones que en él se realicen, y sin perjuicio de las facultades de sus demás gerentes y apoderados, se designa como representante especial a don Domingo Lama Astaburuaga, cédula de identidad N°16.360.767-0, Country Manager de ElBoliche.cl SpA, domiciliado para estos efectos en Av. Catedral 1.401, piso 14, oficina 1401Santiago. Su personería consta en escritura pública de fecha 22 de enero de 2019, bajo el repertorio N°7.957-2019, de la 2° Notaría de Santiago de don Francisco Leiva Carvajal, ubicada en Amunátegui N°73, Santiago.</p>
            
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"black", marginBottom:50}}>17. Solución de controversias</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey", marginBottom:50}}>En caso de existir una controversia, siempre podrás acudir ante el tribunal competente, de conformidad a las disposiciones de la Ley 19.496.</p>

            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"balck", marginBottom:50}}>Validez y vigencia de estos T&C</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey"}}>Versión actualizada al 31 de marzo de 2022.</p>
            <p align="justify" style={{fontWeight: 500, fontSize:19, color:"grey", marginBottom:100}}>Estos T&C han sido reducidos a escritura pública, como se expresan aquí, en la 2ª Notaría de Santiago de D. Francisco Leiva C., ubicada en Amunategui N°73, Santiago, bajo el Repertorio N° 24.288 , de  2022 y  rigen desde esa fecha y reemplazan a cualquier otro. Sólo podrán variar en virtud de otra reducción a escritura pública de términos y condiciones, y desde la fecha de ella.</p>
        </div>
    </div>
  )
}
export default info;